### ISSUE TITLE
Click on costum mesh

### ISSUE THREAD

**Issue by andrewtheone** [andyhall/noa#1]
I have added a entity via .add(...) with custom mesh, how can i get a callback if the player clicks on it?

**Comment by andyhall** [comment]
Hey, cheers for trying this out!

There's nothing like this built into noa at the moment, but Babylon.js, the underlying 3D engine, has such a feature. I haven't used it much but it's explained [here](https://github.com/BabylonJS/Babylon.js/wiki/11---Picking-collisions), I believe it should sort you out!
