### ISSUE TITLE
Using imported models (gltf) for entities (players). [Question]

### ISSUE THREAD

**Issue by Patbox** [andyhall/noa#100]
I'm trying to use gltf model for player, but it doesn't seem to work. Here's code, that I'm trying to use:
```
BABYLON.SceneLoader.ImportMesh(["bone"], "./models/", "player.gltf", scene, function (meshes, particleSystems, skeletons) {
 var playerModel = meshes //Mesh.CreateBox('player', 1, scene)
	var eyeOffset = 0.9 * noa.ents.getPositionData(noa.playerEntity).height

	// offset of mesh relative to the entity's "position" (center of its feet)
	var offset = [0, h / 2, 0]

	noa.entities.addComponent(eid, noa.entities.names.mesh, {
		mesh: playerModel,
		offset: offset
	})
}
```

And error:
```
Uncaught TypeError: Cannot read property 'copyFromFloats' of undefined
    at eval (mesh.js:52)
    at Array.forEach (<anonymous>)
    at Object.renderSystem (mesh.js:48)
    at eval (ECS.js:508)
    at Array.forEach (<anonymous>)
    at Entities.ECS.render (ECS.js:505)
    at Engine.render (index.js:365)
    at GameShell.onRender (container.js:64)
    at GameShell.emit (events.js:152)
    at render (shell.js:426)
```

Model, that I'm trying to use
[player.gltf.zip](https://github.com/andyhall/noa/files/4559726/player.gltf.zip)

**Comment by andyhall** [comment]
Hi, not sure this is a noa issue but at a glance it looks like that babylon function returns an array of meshes. Did you try:

`var playerModel = meshes[0]`

or similar?

**Comment by Patbox** [comment]
No errors, but it doesn't load entire model. I've also checked and program I used generated array of meshes.

**Comment by andyhall** [comment]
Hi, if your model has multiple meshes then I'm guessing that the extra ones (after the first, which you're passing to the mesh component) need to be passed to `noa.rendering.addMeshToScene`. Behind the scenes noa does several extra bits of management on meshes, and that API sets them all up. It gets called automatically for meshes that are managed by the mesh component.

If you do that I think the extra meshes will render, but I'm not sure if they'll move around with the player or not. I imagine it depends on whether or not the meshes have parent/child links set up that Babylon recognizes. If they don't move around, the easiest fix would probably be to make a render event listener that copies the main mesh's position to the other meshes. But it might also work to manually set up whatever parent/child links they need.

In code:

```js
var playerModel = meshes[0]
noa.entities.addComponent(eid, noa.entities.names.mesh, {
    mesh: playerModel,
    offset: offset
})

var extras = meshes.slice(1)
extras.forEach(mesh => noa.rendering.addMeshToScene(mesh) )

// if the extra meshes don't move around...
noa.on('beforeRender', dt => {
    extras.forEach(mesh => { 
        mesh.position.copyFrom( playerModel.position )
    })
})
```

Or something like that. I haven't tested that, just guessing.

Alternate guess: there may be some Babylon issue that I don't know anything about. Babylon is the 3D engine that noa uses, and it has a lot of features for handling bone animations and whatnot, but I've never used them. There is a very active [forum](https://forum.babylonjs.com/) where you may be able to find help though.

**Comment by Patbox** [comment]
It works! Thanks for help :)
