### ISSUE TITLE
Better place to ask questions?

### ISSUE THREAD

**Issue by Heath123** [andyhall/noa#101]
It doesn't seem like GitHub issues are the best way to ask questions. Do you have any other way to ask questions like a Discord server or something else? If not, would you consider making one?
Thank you

**Comment by andyhall** [comment]
Hi, for `noa` questions right now this is the place - I figure that doing Q&A here means that the answers stick around for anyone who checks the issues to see if their question has been answered.

A discord would make sense if more people were involved, but at the moment I'm not sure anyone can really answer questions besides me :)

Note though that for anything Babylon related, there's a really active [forum](https://forum.babylonjs.com/).
