### ISSUE TITLE
Image artifacts with textures on blocks when moving

### ISSUE THREAD

**Issue by Jarred-Sumner** [andyhall/noa#108]
Sorry to bother you again

This color thing is always present, but its especially noticeable when moving:
![gifgif](https://user-images.githubusercontent.com/709451/81031465-30257100-8e41-11ea-950a-c176d4192242.gif)

At first I thought it was an artifact from running a PNG optimizer on all the textures, so I tried without that but the textures look the same.

I also looked at this thread https://forum.babylonjs.com/t/help-on-eliminating-annoying-artifacts/5452 and tried:
```ts
scene.getEngine().setHardwareScalingLevel(1 / window.devicePixelRatio);
```

and

```ts
  const pipeline = new DefaultRenderingPipeline(
    "defaultrendering",
    false,
    scene,
    [scene.activeCamera]
  );
  pipeline.fxaaEnabled = true;
  pipeline.samples = 4;
```

I also tried setting `lightSpecular` to `[0,0,0]`, `[1,1,1]` and the clearColor of the scene but none of these made a big difference

Any ideas what might cause this?

**Comment by andyhall** [comment]
I'm not much of a 3D expert, but it looks like a job for anisotropic filtering to me? I believe in Babylon filtering can be set per-texture, but IIRC there are some webgl limitations - e.g. I think on windows you can't have anisotropic filtering and nearest-neighbor filtering (i.e. pixelated textures) at the same time, you have to choose one or the other.

But note I don't know any Babylon-specific details here, like whether there's a markAsDirty flag you need to set after changing these sorts of properties.

**Comment by Jarred-Sumner** [comment]
Sounds good I'll look into anistropic filtering
