### ISSUE TITLE
Block Outline doesn't switch color 

### ISSUE THREAD

**Issue by johno1566** [andyhall/noa#109]
I have tried to change the default Block Highlighting color by changing code. Why isn't it switching?
![image](https://user-images.githubusercontent.com/32988429/81039789-c6b45b00-8e5e-11ea-92b9-7c246767fd59.png)

**Comment by andyhall** [comment]
Hi, Babylon's [Color3](https://doc.babylonjs.com/api/classes/babylon.color3#constructor) takes `0..1` float arguments.

**Comment by johno1566** [comment]
Thank You :)
