### ISSUE TITLE
An option for DeviceOrientationCamera would be nice

### ISSUE THREAD

**Issue by terrac** [andyhall/noa#11]
I checked out DeviceOrientationCamera and I can view in 3d by tilting my phone. http://doc.babylonjs.com/tutorials/Cameras

Having an option for the phone to do that would be nice

**Comment by andyhall** [comment]
Hi, thanks for the tip and sorry for the late reply! This is a neat feature, but I want to keep this library  focused on managing voxels, and leave things like player and camera movement to be handled by client code (i.e. the app that's using this library). 

It should be possible for the client to remove the default camera and replace it with a new one though, I think? (I haven't tried this, it might require a bit of hacking)

Thanks!
