### ISSUE TITLE
How to make realistic terrain.

### ISSUE THREAD

**Issue by csf30816** [andyhall/noa#125]
I've been using Simplex noise to make the terrain for my voxel game using your engine. The result is okay but it's pretty much all hills. So I made another noise that's flatter and interpolated them together using another noise value. It still isn't what I want.

I am wondering how I could achieve realistic terrain with **flatlands**, **mountains**, **cliffs**, **hills**, and **natural-looking water spots** (right now ALL my water spots are surrounded by hills/mountains and are very steep/deep). I've been searching the internet and couldn't find much. I went here as a last resort to hope somebody knew this stuff better than me.

My current code:

```js
const mountains = noise(x * 0.01, z * 0.01, 3 /*octaves*/) * 50;
const flatlands = noise(x * 0.05, z * 0.05, 1) * 10;
const value = 0.5 + noise(x * 0.01, z * 0.01, 1) / 2; // Normalize since noise returns -1 to 1

const height = lerp(mountains, flatlands, value);
```

also, it'd be nice to know how to do rivers :)

**Comment by csf30816** [comment]
So I just tried something that made it look a bit better. I made a BIG LONG base ground that made it look better. Then I subtracted in the water parts to make it deeper. I am currently trying to add mountains but when I do there is a huge cliff seamline where the mountains are added and where the mountains were not added. I tried fixing that with *interpolation* but that wrecked the oceans *interpolation* and made a big cliff border in the ocean. I'll update if I find a solution.

**Comment by andyhall** [comment]
I'm afraid the big-picture answer here is: it's a really hard problem, and if you find a simple solution let me know. 😁 

But things you're doing are all good approaches. Note that the thing you're doing, where you add together several different noise values, with different wavelengths and amplitudes, is essentially the same thing that the "octaves" parameter on the noise function. That is, one noise function with octaves=2 is equivalent to adding together two noise functions, where the same has half the wavelength and half the amplitude of the first.

One thing you might try is having biomes, i.e.:

```js
var biomeNoise = noiseFunction1(x/500, z/500)
if (biomeNoise > 0) {
    // create mostly flat terrain
} else {
    // create mountainous terrain
}
```

and so on. Of course code like the above would have discontinuities at the border between biomes, so you might want smoothing there etc.

For rivers and tunnels, the only good approaches I know of are really slow (e.g. 3D noise). Maybe other folks have good ideas...

**Comment by csf30816** [comment]
I might try 3D noise for tunnels. Your code is very similar to my new code except I interpolate them, the downside of that is you never really get the truly flat areas or the truly mountainous areas (only small hills and big hills) but it gets flat toward the ocean and overall looks nice.

**Comment by csf30816** [comment]
I'm just gonna close this as it isn't really an issue or anything. I am still developing a realistic algorithm but this is unrelated to noa
