### ISSUE TITLE
Typescript migration branch

### ISSUE THREAD

**Issue by andyhall** [andyhall/noa#135]
This issue is to track the status of the typescript migration work from @SamKirkland.

I'm definitely interested in trying this out, but also not sure I want to change languages. However either way I'm heads-down on my game client work at the moment so I have not yet done all the stuff I'd need to do to build against a TS library. So for now I'm merging the PR (mostly sight unseen) into its own branch, so that anyone who wants to build their project against it can do so.

Please let me know if anything about the current branch setup prevents TS users from building against this branch...

**Comment by Patbox** [comment]
I think it would be useful to have already transpiled copy in the repo, so users can use use `npm i`.

Also after using transpiled version, I'm getting some errors, but it might be something I did wrong.
![image](https://user-images.githubusercontent.com/39821509/97327403-371fc000-1875-11eb-94a1-3108f978cf72.png)

**Comment by sourcerose** [comment]
got that error too, just restart your PC, then do `npm i`

**Comment by andyhall** [comment]
Weird, I'm certain I replied to this.... I think I was on shaky wifi at the time.

I'm afraid I haven't used TS and don't have a toolchain set up for it, so I can't really build or test anything. I can pull in a PR for one of course if it's useful though.

No idea about the error though. It might be the same as #142, which seemed (?) to be some kind of npm bug, which seemed to go away once you run `npm i` a second time.

**Comment by FractalHQ** [comment]
I have a clone where I've been attempting to modernize the codebase to minimum ES6 standards.  Getting rid of require(), node built-ins, refactoring the OO/class based structure to a more functional approach, using modern export syntax and cleaning up comments to use JSDoc.  I wanted to do this before rewriting to typescript to make my life easier, but TIL there's already a Typescript fork.

Noa should be in Typescript, 100%.  It will improve DX, types, and enforce modern structure among other benefits.

I would be happy to scrap what I've done to work on the Typescript fork!

**Comment by FractalHQ** [comment]
FYI, my vite/rollup version is using Svelte for UI.  Many consider Vite (built on rollup) the successor to Webpack- but it only supports ES6.  So the only real difference in my clone is the change of all uses of `require()` to `import` (and const/let in place of var which isn't necessary but helps squeeze out a [bit more performance](https://stackoverflow.com/a/54235130)).  Aside from that, I had to do some minor modifications to `micro-game-controller` and the `Buffer` hack.

I also added the sprint and crouch found in one of the TODOs.

Not sure if the clone would be useful to you or anyone else, but if so, let me know!

Regardless, thank you for your work on this awesome project!!  You're a wizard with this stuff.

**Comment by andyhall** [comment]
Hi, sorry for the slow replies. The main reason I'm hesitant about converting to TS is that, noa being strictly a dependency, it would (I assume?) mean that all client apps would have to convert to TS as well (or at least start building via the TS compiler) even if they aren't currently.

But the ideal situation would be if client apps using TS get the benefits of using noa as if it was a TS library, while non-TS projects can still build noa directly without `tsc`.

Can someone who's more familiar with TS confirm that that makes sense and is possible? I guess this would be done by adding definition files to noa, which would hopefully be autogenerated from the library source. Or is there more to it than that?

If this is the right way to go, it would be very helpful if a TS user could create some kind of "sample TS game client" repo, which functions like `noa-examples` but uses TS. Something I could clone and `npm i` and then see whether it's building correctly, getting the right autocorrect, and so on.

@FractalHQ can you advise?

**Comment by Patbox** [comment]
> Hi, sorry for the slow replies. The main reason I'm hesitant about converting to TS is that, noa being strictly a dependency, it would (I assume?) mean that all client apps would have to convert to TS as well (or at least start building via the TS compiler) even if they aren't currently

That's not the case, if library is pre compiled to JS before being publisher (most do that, including BabylonJS). 

It would benefit both, as TS definition files would be more accurate and autocomplition would work better.

**Comment by andyhall** [comment]
Ah, of course that makes more sense. Is it set in stone that client apps always import prebuilt JS, or could a JS app import prebuilt files while a TS client skips that and imports from the TS?

**Comment by Patbox** [comment]
Generally most will use prebuild JS, as it's easier to import (npm) and it's supported by all bundlers. There won't really be a difference while developing with TS files anyway, as definitions will be identical. Only case where it will matter is when someone copies into project/modifies engine itself, but it shouldn't be a problem

**Comment by andyhall** [comment]
Thanks. And to check, this JS prebuild pattern will work normally even though noa imports from Babylon as a peer dependency, and Babylon won't be present during the pre-build step? Or does that change things?

**Comment by Patbox** [comment]
It will complain while compiling/writing code for sure, but downloading it while still declaring it as peerDep should work just fine

**Comment by andyhall** [comment]
Wouldn't that mean that most of Babylon would get included in the final bundle twice, being imported into both the prebuilt engine bundle and the client code?

**Comment by Patbox** [comment]
If you use tsc for that it shouldn't bundle anything (it only transpiles it to js and d.ts files). Distribution itself should still look the same

**Comment by andyhall** [comment]
Hi, I've been working on this, though to be honest it's a pretty nightmarish mess of gotchas.

One big question for @SamKirkland. In your migration branch, how did you go about creating type declaration files for child modules? (`game-inputs`, `voxel-physics-engine`, and so on.)

I'm trying to do this naively, with something like:

```shell
npx tsc node_modules/game-inputs/inputs.js
   --allowJs --declaration --emitDeclarationOnly --target esnext 
   --outfile types/vendor/game-inputs/index.d.ts
```

But this doesn't seem to generate anything `tsc` is happy with - it sets the wrong module names, treats non-class functions as classes, etc., and I don't follow why. Did you hand-author the `.d.ts` files in your branch, or did you generate them somehow?

**Comment by andyhall** [comment]
Hi, I've pushed a big revision in this direction. It would be great if anyone using noa with a typescript client could check whether it breaks your game.

The code is in branch `#typedec-migration`. What it does is, `noa` itself is still in JS, but it's now typescript-friendly enough that `tsc` can generate type declaration files from the source. The branch has `.d.ts` files generated this way, and they're listed in package.json, so if you clone this branch and import it you should get quality code hints (in VSCode anyway) that will stay in sync with the library going forward.

As a bonus, there's now a real API reference built with `typedoc`.

Note there are two breaking changes in this branch:
 * Engine is now a named export, so change `import Engine ..` → `import {Engine} ..`
 * noa's `getBlock`, `setBlock`, `addBlock` methods now require separate (x,y,z) parameters. (they used to optionally accept an array)

That's it. Feedback from any typescript users would be really helpful!

**Comment by Patbox** [comment]
I didn't have time to test it, but at first glance it looks like major improvement. I plan to start rewriting my game soon so it lined up perfectly :)

**Comment by andyhall** [comment]
Thanks for looking. It would be great if you get a chance to try building with it, I'd like to push this out as a new version update once someone can confirm it doesn't break their builds.

**Comment by Patbox** [comment]
First test with pre-rewrite VoxelSrv:
- There are few missing types in Entities (getState, deleteEntity, createComponent and possibly more)
- Entities setPosition isn't reverted (as claimed)
- Engine.on requires Function, which doesn't work with simple callbacks (changing type to `(...args: any[]) => void` or just any should fix that)
- Registry registerMaterial requires all 5 arguments
- rendering addMeshToScene requires all arguments
-

**Comment by andyhall** [comment]
Thanks for checking. On the last two, I did a pass over everything marking optional parameters - hopefully should be right now.

On the 1st and 3rd, do those prevent you from building, or are they just missing type information? Those types are coming from type files that I build with tsc and am hoping not to need to hand-author (but maybe that's not possible).

2nd point, sorry you lost me.

**Comment by Patbox** [comment]
1st and 3rd is just missing type info, it builds just fine.

For 2nd, it looks like setPosition (and set/getBlock) was changed with this [commit](https://github.com/andyhall/noa/commit/c00b5c30433b16d3be8bc826b3a3d6e4762a2d4f) to only allow arrays (before it allowed passing x, y, z by itself), but later [this commit](https://github.com/andyhall/noa/commit/7b92d77eb8ec35c775c9304393a7f87656db3430) reverted this change for set/getBlock, but not setPosition

**Comment by andyhall** [comment]
Ah I missed that. Okay, I pushed that revert. The missing types, I'll leave for now - the right fix is to revise the ECS library so that it emits proper types of its own.

Thanks for checking, if it's otherwise okay for you I'll push this to the main branch soon (way overdue for a release...)

**Comment by Patbox** [comment]
I didn't find any other problems, so you can push it!

**Comment by andyhall** [comment]
Thanks again for checking! 

I'll close this issue for now, but please open new ones down the road for any specific typescript-interop issues (like exposing better type decs for dependencies).
