### ISSUE TITLE
When I load world from json some cube not rendered completely

### ISSUE THREAD

**Issue by nabilove** [andyhall/noa#136]
![issue](https://user-images.githubusercontent.com/5945183/97318761-94e6e480-1842-11eb-91d6-6e2f3acaf6a5.png)

would you know how to fix that or do you need more info

**Comment by Patbox** [comment]
Quickfix: Try setting `noa.world.minNeighborsToMesh` to lower values (6 is default)

It looks like there aren't any chunks above it, so engine doesn't mesh it.

**Comment by nabilove** [comment]
My world is slow to load too , did you optimize your loading time, have any tips?

**Comment by Patbox** [comment]
First thing you should use json for storage (instead use binnary data).
You can also move some of the work to webworkers

**Comment by nabilove** [comment]
Waths your discord I want to talk, if your not too shy

**Comment by nabilove** [comment]
I'm good
