### ISSUE TITLE
Use GPU to speed up the Performance

### ISSUE THREAD

**Issue by sourcerose** [andyhall/noa#143]
This is an enhancment that might take a long time to develop but I think it could greatly improve Performance. Also I already know BabylonJS already uses the GPU. However, the functions within Noa are what is using a lot of CPU.
 https://github.com/gpujs/gpu.js/ could greatly help with the Performance of the engine.

**Comment by andyhall** [comment]
Hi, I'm certainly open to suggestions if you have any specific ideas for what processing could be done on the GPU. 

But AFAIK the heavy CPU processing in noa is mainly meshing and things like physics, which I would imagine are too tightly coupled to local state to be offloaded.

**Comment by sourcerose** [comment]
You're right. Sorry for the waste of time.

**Comment by andyhall** [comment]
Hi, not at all, it would be great if anyone knows any ways to make it work. Personally I know very little about GPGPU, so I'm only guessing about what is/isn't feasible.
