### ISSUE TITLE
How do I set the rotation of the playerEntity?

### ISSUE THREAD

**Issue by Trenki** [andyhall/noa#149]
I want to change the rotation of playerEntity. Can you give me some suggestions?Thank you very much.

[playerEntity](https://static1.cxy61.com/bcgame_face2face/27626/6238705460b929d8b4f1a30ec22fd67d_k.png-782x688)

**Comment by andyhall** [comment]
Hi, are you wanting to rotate the mesh that's associated with the player entity? Or to rotate which direction the player is moving in?

If the former, then any entity has the [`mesh` component](https://github.com/andyhall/noa/blob/master/src/components/mesh.js) to the player entity, then you can get that mesh and change its rotation by setting the necessary [babylon.js properties](https://doc.babylonjs.com/divingDeeper/mesh/transforms/center_origin/rotation). E.g.:

```js
var meshData = noa.entities.getMeshData(noa.playerEntity)
meshData.mesh.rotation.set(0, yRotation, 0)
```

If you want to change the player entity's move direction, the [heading](https://github.com/andyhall/noa/blob/master/src/components/movement.js#L21) property of the `movement` component tracks that. By default the [receivesInput](https://github.com/andyhall/noa/blob/master/src/components/receivesInputs.js) component updates this property, and then the movement physics uses it when deciding how to move the entity.

**Comment by Trenki** [comment]
Thank you very much, Andy. That was really useful.At the same time, I also wanted to find the mesh of the camera so as to change the Angle of the camera, but I failed.

**Comment by andyhall** [comment]
The easiest way to get the camera heading is to read `noa.camera.heading` (radians). So, e.g. a minimal way to make the player entity mesh follow the camera would be:

```js
noa.on('beforeRender', () => {
    noa.ents.getMeshData(noa.playerEntity).mesh.rotation.y = noa.camera.heading
})
```

**Comment by Trenki** [comment]
I didn't make myself clear.I want to use the following code to remove the camera from following Player, and then set the camera properties separately, as in Babylon.
```javaScript
// make cameraTarget stop following the player
noa.ents.removeComponent(noa.camera.cameraTarget, 'followsEntity')
// control cameraTarget position directly (or whatever..)
noa.ents.setPosition(noa.camera.cameraTarget, [x,y,z])
```

**Comment by andyhall** [comment]
Sorry, I'm pretty lost as to what you want to do here. If you want to make the camera stop following the player entity and control it directly, the code you posted should work for setting the position:

```js
noa.ents.removeComponent(noa.camera.cameraTarget, 'followsEntity')
noa.ents.setPosition(noa.camera.cameraTarget, 5, 5, 5)
```

Do you mean that you also want to directly control the camera's rotation? If so, you can do that via noa APIs:

```js
noa.camera.heading = 0.5
noa.camera.pitch = 0.2
```

However the engine will automatically apply mouse inputs to the camera rotation, and there's currently no API to disable that. You could work around it by setting the sensitivity to 0, which will effectively prevent the mouse from affecting the camera, and then undo it later...

```js
// disables built-in mouse control of camera
noa.camera.sensitivityX = noa.camera.sensitivityY = 0
```

If you just want to bypass everything and get a reference to babylon's camera object, then you're looking for `noa.rendering._camera`. But you may find that directly updating the camera leads to e.g. temporal aliasing, or other issues that are difficult to fix.

**Comment by Trenki** [comment]
`noa.camera.heading` and `noa.camera.pitch` is what I am looking for, thank you, my problem has been solved.
