### ISSUE TITLE
#develop issue possibly relating to dropped frames

### ISSUE THREAD

**Issue by MCArth** [andyhall/noa#155]
Hi, I was having a look at pulling in from the develop branch due to the performance optimisations you've made and encountered some issues. I'm encountering a bug that involves something feeling like failed movement prediction and then movement correction. I've attached a video of a repro in test. (see about 11 secs in) I was experiencing it much more in my game though I wasn't consistently teleporting so far - I think it may be related to dropped frames.

https://user-images.githubusercontent.com/26874892/110464369-f6f60700-80ca-11eb-942a-c7d38eb4e569.mp4

Maybe you're aware of this already (it is the develop branch!), apologies if so. Is there a stable commit on develop I could pull in?

**Comment by Patbox** [comment]
I can confirm this issue

**Comment by andyhall** [comment]
Hi, I think this is a regression of a bug I had earlier with how the shell sends timing events - basically an edge case makes the engine thing that a frame happened with a negative duration.

Let me have a look..

**Comment by andyhall** [comment]
Hi, try the newest dev branch to fix this. Or if you have a local fork, update this dependency:

```
"micro-game-shell": "0.2.0",
```

Thanks!

**Comment by andyhall** [comment]
This should be fixed in #develop, let me know if it's still happening for anyone.
