### ISSUE TITLE
Since latest commit, custom meshes of blocks are in wrong position

### ISSUE THREAD

**Issue by Patbox** [andyhall/noa#157]
Since [this](https://github.com/andyhall/noa/commit/b928e16a17f1f1ff10e66e0eeb8755c1b6f75faf) commit blocks that use custom meshes are in wrong place.

Before:
![image](https://user-images.githubusercontent.com/39821509/111899570-c056af80-8a2d-11eb-8f0f-5303bb4747aa.png)
After:
![image](https://user-images.githubusercontent.com/39821509/111899635-35c28000-8a2e-11eb-9121-47674035c134.png)

These meshes are still added to the world, but at y = 0

**Comment by andyhall** [comment]
Hmm - I drastically changed how custom meshes are handled, but they're positioning correctly for me. If you build the `noa-examples` worlds using the current develop engine, do custom meshes work correctly for you? Your game might be doing something I didn't expect and need to account for.

**Comment by Patbox** [comment]
I can't recreate it on noa-examples. It doesn't too much of custom logic for it and mesh is created from [simple function](https://github.com/VoxelSrv/voxelsrv/blob/a3b0a841af48155041961daf355abc6aa0bbf06c/src/lib/gameplay/registry.ts#L147).

**Comment by Patbox** [comment]
Okay, I can replicate it on noa-examples by changing playerStart to [0.5, 100, 0.5] (I also replaced one block in worldgen, so it's simpler to check)
![image](https://user-images.githubusercontent.com/39821509/111900972-b5a01880-8a35-11eb-8654-1d0318d03b9d.png)

playerStart = [0, 5, 0]
![image](https://user-images.githubusercontent.com/39821509/111901028-ee3ff200-8a35-11eb-87bd-f7ad695cbbb6.png)

**Comment by andyhall** [comment]
Thank you, I can reproduce!

**Comment by andyhall** [comment]
The test-world reproducing case is now fixed, let me know if it still reproduces in your actual game client.
