### ISSUE TITLE
How to tell the engine to load textures underneath blocks with alpha

### ISSUE THREAD

**Issue by Nesh108** [andyhall/noa#17]
I have been playing around with the testbed and found the `leaf.png`, which is supposed to represent the leaves for a tree. I tried applying it to the ground and this was the result:

![leaf-textures](https://cloud.githubusercontent.com/assets/1250305/23841051/c55f3b58-07ed-11e7-93a1-a52002049b11.png)

It looks like the engine loads only 1 level of blocks (probably for optimization) but that fails when the block `hasAlpha: true`.

**Comment by andyhall** [comment]
Hi,

I think two separate properties are overlapping here. When you register a **material**, you specify a `hasAlpha` to tell whether that material's should have transparency. The engine only uses this for deciding what kind of (babylon) material to create.

Separate from that, when you register a **block** type you specify whether it's `opaque`. This is the setting that determines whether stuff underneath the block gets culled at the meshing stage. From looking at the image, I think all you need to do is make the leaf blocks opaque, and it'll do what you expected.

(Note that blocks also have a property `solid` - this one is for physics, and has nothing to do with rendering.)

Let me know if this works!

**Comment by Nesh108** [comment]
I will try now. But yeah, I was a bit confused with the difference between opaque, solid and so forth.

So:

- Opaque: is whether you can see through it or not
- Solid: is whether you can go through it or not
- Fluid: is basically the opposite of solid (but will be extended when we implement the fluid functionality)

Correct?

**Comment by andyhall** [comment]
Yes, you have it right, and the leafs should not be opaque (that was a typo 😬 ). 

Basically they're all really single-purpose properties. I mean, it probably won't make any sense to have a block that's fluid but solid, or that's opaque but has alpha, but the engine looks as each property in different ways so I have them all separate for now.

**Comment by Nesh108** [comment]
Sweet, I just set `opaque: !hasAlpha` and that works like a charm!
