### ISSUE TITLE
Attempting to understand the code.

### ISSUE THREAD

**Issue by JaegerBomBYT** [andyhall/noa#195]
Could i get an explanation on what this code really means, and how it accomplishes world generation because im honestly stumped

```js
// modify the decideVoxel function to take cx, cz and data as parameters
var decideVoxel = (x, y, z, ht, clo, chi, tree, cx, cz, data) => {
    if (y < ht) {
        if (y < -1.8) return water
        if (y < 1.2) return sand
        return (ht - y < 1) ? grass : dirt
    }
    if (y < ht + tree) {
        var dx = Math.abs(x - cx - data.shape[0] / 2)
        var dz = Math.abs(z - cz - data.shape[2] / 2)

        return log
    }
    return 0 // this is the air
}

// the rest of the code is unchanged
noa.world.on('worldDataNeeded', (requestID, data, cx, cy, cz) => {
    // fast cases when very high/low
    if (cy > 40 || cy < -20) {
        var monoID = (cy > 0) ? 0 : water
        return noa.world.setChunkData(requestID, data, null, monoID)
    }

for (var i = 0; i < data.shape[0]; i++) {
    var x = cx + i
    for (var k = 0; k < data.shape[2]; k++) {
        var z = cz + k
        var ht = Math.sqrt(x * x + z * z) / 100
        var a = noise(x, 150)
        var b = noise(z + 50, 140)
        var c = noise(x - z - 50, 120)
        ht += 2 * a + b + c
        // changed the pillar math to make it shorter and less frequent
        var pillar = (Math.random() < 0.005) ? Math.floor(3 + 2 * Math.random()) : 0 // change the probability and the height range here
        var clo = 39 + 2 * (b - c)
        var chi = 35 + 2 * (a - b)
        for (var j = 0; j < data.shape[1]; j++) {
            var y = cy + j
            // pass cx, cz and data to the decideVoxel function
            var id = decideVoxel(x, y, z, ht, clo, chi, pillar, cx, cz, data)
            data.set(i, j, k, id)
        }
    }
}
```

**Comment by fenomas** [comment]
Hi, to get the big picture it would be easier to start with the [hello-world demo](https://github.com/fenomas/noa-examples/blob/master/src/hello-world/index.js). It has lots of comments explaining the necessary steps for setting up the engine, declaring voxel properties, and so on.

For world generation, the hello-world demo does it in two simple steps:
 1. [This code here](https://github.com/fenomas/noa-examples/blob/master/src/hello-world/index.js#L67-L72) declares a single function that decides the value of every voxel in the world, depending on its `x,y,z` location. E.g. all voxels with a `y` value below 3 are dirt, and so on.
 2. [This code afterwards](https://github.com/fenomas/noa-examples/blob/master/src/hello-world/index.js#L75-L89) is what hooks the logic up to the engine. It registers a listener with the engine, which is called every time voxel data is needed. Then the listener takes 3D data array provided by the engine and calls `getVoxelID` on all of the positions in the array.

Then the code you posted above is basically a more complicated version of the `getVoxelID` function from the hello-world demo. It's doing the same thing - deciding which voxel ID should be placed at each `x,y,z,` location in the world, but it has a bunch of extra logic whose purpose is to make the stress-test world data more complicated. In that version, the `ht` argument is the y-height of the terrain, the `clo/chi` args are the low- and high-points of clouds, and the `pillar` arg is a value for whether or not to add a pillar at that particular `x,z` column.

Hope that helps you get started, let me know what else isn't clear.
