### ISSUE TITLE
Z-fighting in entity shadows

### ISSUE THREAD

**Issue by andyhall** [andyhall/noa#31]
Drawing entity shadows at a fixed offset leads to z-fighting in distant entities, or nearby shadows being drawn noticeably off the ground.

**Comment by andyhall** [comment]
@Nesh108 Hey, I have just pushed an update to develop which tries to fix this issue. Instead of drawing entity shadows at some fixed offset above the ground, it uses a small offset (near 0.01) for nearby entities, scaling up to a larger offset (0.1) when the entity is far away.

I *think* this should fix shadows generally, so there's no need for a tuneable parameter. Can you check if this is the case in your project(s)? If you still get issues (z-fighting or shadows that are noticeably far off the ground), please ping me.

**Comment by Nesh108** [comment]
I will look into it :)
Thanks for checking!

**Comment by Nesh108** [comment]
Heya! Tried your branch and it seemed fine on my side :)

**Comment by andyhall** [comment]
Hey, thanks for checking!

FYI I just pushed some more big changes to develop with some big speed improvements. They probably shouldn't break compatibility, but there's a lot of internal reorganization, so if you are maintaining a forked version of this repo it might take some merging to incorporate them.

But if you have a chance to pull the latest commit in and test, it'd be great to hear about any issues. I'll ping you on the commit!
