### ISSUE TITLE
Any plan to support mobile VR and touch inputs (virtual joystick)?

### ISSUE THREAD

**Issue by Nesh108** [andyhall/noa#32]
Hey @andyhall,

I am currently looking into adding VR support for mobile headsets and some touch inputs for allowing users to play with their phones. 

Are these things in your list?

It would be interesting to have them. Let's see if I can make something conclusive 😄

**Comment by andyhall** [comment]
The short answer is no, I have not done any thinking about this. However, on the mobile side it's "just" a matter of grabbing touch events and wiring them up to `noa.inputs` in some way. That is to say, I think you could support it without any changes to this library but I haven't tried.

For VR, I think Babylon has some kind of support for it but I don't know any details, or what it entails. I think there's a camera for it? So my guess is that a first-blush effort might involve removing the regular camera from `noa.rendering._scene` and adding a different one that's derived from the VR camera? But that's purely guessing!
