### ISSUE TITLE
Great result, but ...

### ISSUE THREAD

**Issue by Codoa** [andyhall/noa#34]
Please do not understand me wrong. But this code is one of the ugliest code I've ever seen.
Ok, I think you're not a professional developer. You have to learn more clean code. And how to develop correctly and responsive. It's not my intention to insult you. The truth can be hard.
Your project is great, but only the result. I'm looking for great REAL voxel engines. And your's is one of the best. But coding ... 
One of the important rule for coding is: Do not code for you, Do it for others. Do not confuse the readers. Do not complicate it, to appear more intelligent. 

Tip:
You could develop with typescript and build with gulp. Code with visual studio code.

**Comment by andyhall** [comment]
Thanks for the feedback, but nothing here is specific enough to be actionable. If you think code in this repo should be changed, please open a new issue that specifies what code you're talking about and what you think is wrong with it.

**Comment by IceHacks** [comment]
typescript is stupid

**Comment by Heath123** [comment]
This code looks clean and well-documented to me, but I'm no expert

**Comment by andyhall** [comment]
This issue is a few years old folks, let's leave it to posterity 😉
