### ISSUE TITLE
Browsers Supported?

### ISSUE THREAD

**Issue by multiplayer-shop** [andyhall/noa#43]
Hello,  I'm on Mac OSX 10.6.8  Chrome Version 49.0.2623.112 (64-bit) and the screen moves wildly when I allow pointer lock. In addition the block selection is not where my cursor is. (same in Firefox) It all performs well in terms of speed, its just very hard to control.

What OS/Browser does this work properly in? Thanks, Joel

**Comment by andyhall** [comment]
Hey - sorry, afraid I don't know precisely which browser versions work well. But Chrome 49 is pretty old - I think the current version is 63. Is it feasible to upgrade? (I develop mainly in OSX/Chrome so in general that should work reliably.)

**Comment by multiplayer-shop** [comment]
Thanks!
