### ISSUE TITLE
Latest version of babylon throws an error on setting a block on chrome

### ISSUE THREAD

**Issue by terrac** [andyhall/noa#50]
Cannot add an uniform after UBO has been created.

This doesn't have any impact as far as I can see, but it seems like something to be aware of.

**Comment by terrac** [comment]
Looks like the issue isn't appearing anymore so I closed.

**Comment by terrac** [comment]
This seems to happen on an intermittent basis.  The latest version of babylon being 3.2

**Comment by terrac** [comment]
It looks like I managed to fix it via not doing alpha textures on blocks and not registering block id #1.

Not sure exactly why though.

**Comment by Vinc3r** [comment]
I have this bug too (but unfortunatly doesn't know how to reproduce it). Today I have it when trying to change the materials on an object:

```JAVASCRIPT
var myPBRMaterial = new BABYLON.PBRMaterial("myPBRMaterial", scene);
var myMesh = scene.getMeshByName("myMesh"));
myMesh.material.subMaterials[0] = myPBRMaterial;
```
Note that the default material is a standard one, and I use a babylon file exported from Blender (2.79b, last version of exporter, BJS v3.3.0-alpha.12).

But a few days ago this was happen when using a spheremap in a reflection channel of a standard material (not assigning in javascript, but already in the .babylon file)

**Comment by Vinc3r** [comment]
erf sorry I totally doesn't seen that I'm not on the babylonjs github... sorry to be miles away :-D

**Comment by valentinbdv** [comment]
Same thing for me, wanted to try the new babylonjs version 3.3.0 but it throws me that error. Only happen with some specific model exported from blender so might be related to that.
