### ISSUE TITLE
Andy Question

### ISSUE THREAD

**Issue by levlups** [andyhall/noa#62]
first of all amazing work , too good to be true , amazing programming , Andy Im trying to accessMeshParticleSystem library from another part of the script , to be honest with you I dont know nothing about ES6 only javascript , how do we access libraries it puzzles me ,thanks

**Comment by andyhall** [comment]
Hi, thanks for the kind words!

Let's see, you mean using the brand new ES6 version I pushed like yesterday right? And do you mean the Babylon.js particle system? If so, then I think the steps to be aware of are:

1. make sure your project has babylon as a dependency  
i.e. `npm i --save @babylonjs/core`
 
2. In your JS, import the specific babylon module:   
```js
import { ParticleSystem } from '@babylonjs/core'
console.log(ParticleSystem)
```

I think that's all there is to it.. but I think Babylon has several different particle systems, and I don't know the details on how they're imported or used.

Does that help?

**Comment by andyhall** [comment]
PS: if you don't want to mess with granular imports, you may find it easier to do:

```js
import * as BABYLON from '@babylonjs/core'
window.BABYLON = BABYLON
```

at startup, and then I think you should be able to just reference `BABYLON.Mesh.whatever` like before.

**Comment by levlups** [comment]
sorry I think you misunderstood me , I have been using your engine for a  week now  , I added NPC and FOG and a watermesh , so your engine is running fine , wath Im trying to do is make the blocksmoke particles collide with terrain .how would I proceed with that

**Comment by andyhall** [comment]
Ah, I understand now. Noa doesn't have any particular features related to particles. If you're starting from scratch, I believe Babylon has some particle modules or similar - it's a really full-featured 3D engine. Or, if you mean are already working with particles but you need to make them collide with terrain, the basic answer would be to change their position update function to check terrain when they cross a voxel boundary - the function to do that is:

```js
noa.world.getBlockSolidity(x, y, z)
```

Does that help any?

**Comment by levlups** [comment]
ok screw the particle collision , no big deal lol , Andy i tried to load and obj file or glb and it doesnt work ,I know how to connect a mesh to an entity ,but mesh from file not working ,is it just me or its like impossible and the forums are horrible no help , I have been breaking my head over this for days , do you know how to do it ,my poor hero has no shovel to play with 
![cooldude](https://user-images.githubusercontent.com/52762684/63266572-35647080-c25e-11e9-80f4-44c60e11dca1.png)
