### ISSUE TITLE
Andy how can I make the top face of a block darker 

### ISSUE THREAD

**Issue by levlups** [andyhall/noa#65]
Andy how can I make the top face of a block darker 
I will use your reply to program a shadow system

**Comment by levlups** [comment]
or tell me how to make the whole block darker the next time I place him thanks

**Comment by levlups** [comment]
give me some hints and when I figure it out ill share the discovery

**Comment by levlups** [comment]
example   reg.registerMaterial( 'dirt',       [0.45, 0.36, 0.22],  'dirt.png' )
but if I do this   reg.registerMaterial( 'dirt',       [0.45, 0.36, 0.22 ,**0.5**],  'dirt.png' )
dirt becomes see through but if I do this  reg.registerMaterial( 'dirt',       [0, 0, 0 ,1],  'dirt.png' )
the dirt doesnt become black why is that !!!!

**Comment by andyhall** [comment]
Re: changing the top of a block, when registering a block you can pass in an array of six materials for each face - see (here)[https://github.com/andyhall/noa-examples/blob/master/src/test/index.js#L93].

On the latter question: current behavior is that when you specify both a color and a texture, noa [ignores the color](https://github.com/andyhall/noa/blob/master/src/lib/registry.js#L296), to make sure the texture displays as expected. The easiest way to get around this is to [pass in a custom Babylon material object](https://github.com/andyhall/noa-examples/blob/master/src/test/index.js#L75) - that way you can completely control the diffuse/emissive/specular colors and textures and everything.

**Comment by levlups** [comment]
I found a quick and dirty solution but the game is acting wacky or I missed something

var dirtlitID,dirtID, grassID, stoneID, block1ID, cloudID, leafID, flowerID, woodID, waterID,topwaterID

function registerBlocks(game) {
  var reg = game.registry

  // materials used by block faces
 reg.registerMaterial( 'dirtlit',[1,1,1],  'dirt.png' )
  reg.registerMaterial( 'dirt',       [0.6, 0.6, 0.6],  'dirt.png' )
  reg.registerMaterial( 'grass',      [0.22, 0.38, 0.01],  'voxelGrass.png' )


  dirtlitID = reg.registerBlock( 'dirt', ['dirt','dirt','dirtlit','dirt','dirt','dirt'] )
  dirtID=reg.registerBlock( 'dirt','dirt')
  grassID = reg.registerBlock( 'grass', ['grass', 'dirt', 'grass_side'] )


but the when I do this 
if(game.getBlock(loc[0],loc[1]+2,loc[2])===0){
	  
						 game.setBlock(1,[loc[0],loc[1],loc[2]])
  }else{
	  console.log('shadow');
	  game.setBlock(2,[loc[0],loc[1],loc[2]])
  }

the game doesnt recognize my new block it puts a grass block ??? ,my computer hates me

**Comment by levlups** [comment]
found a quick and dirty way 
 dirtlitID = reg.registerBlock( 'dirtlit', ['dirt','dirt','dirtlit','dirt','dirt','dirt'] )
  dirtID=reg.registerBlock( 'dirt','dirt')

if(game.getBlock(loc[0],loc[1]+2,loc[2])===0){
	    console.log('shadow');
						 game.setBlock(2,[loc[0],loc[1],loc[2]])
  }else{
	
	  game.setBlock(1,[loc[0],loc[1],loc[2]])
  }

its going to double or triple my coding ,but it should suffice now lol

**Comment by andyhall** [comment]
Hi, keep in mind that if lighting is the main issue, Babylon has a lighting system... noa adds a light by default, but you can it from `scene.lights[0]`, and remove it or replace it with something else, etc.

(However I think by default Babylon limits the number of lights that affect a given mesh, to 3 or 4 or so..)
