### ISSUE TITLE
Texture/Material limit

### ISSUE THREAD

**Issue by andrewtheone** [andyhall/noa#7]
I have a world, with 129-131 (129 which are registered by me, and plus 2 by the engine itself) and 143 materials.
My problem is, when I'm about to register/use the next texture, and place a block with the texture and it wont show up. In networking tab I cannot see the new texture it seems like babylon doesnt even try to download it (most of the time), and I get a corresponding ID and can get the material texture and etc from registry by ID, but it just does not show up. Any idea?

**Comment by andrewtheone** [comment]
![image](https://cloud.githubusercontent.com/assets/798506/12069373/18a9ab2e-b02c-11e5-8e63-dc52d2cd4d42.png)

![image](https://cloud.githubusercontent.com/assets/798506/12069376/24110df4-b02c-11e5-8efd-b5b7cd6d528d.png)

**Comment by andrewtheone** [comment]
The front and back or left and right sides are not visible from the outside, but from the inside only. same true for bottom and top sides, after the 130th texture

**Comment by andrewtheone** [comment]
I'm using 128*128 images, I thought I give it a try with 32*32 and 64*64 images. The result is the same. The strangest part is that, Rendering calls the registry asing for texture, even creates a BabylonTexture but it just  does not render correctly, and wath is more strange is that:

texture_id 1- wood
texture_id 2 - grass
...
....
texture_id 128 - cobblestone

when I add something with texture id > 129 or 130 the above image is rendered. when I press f5 (all the blocks and everything is stored on the server, so when it reloads it requests all blocks and displays them, first it loads all the textures and the answers the "worldDataNeeded" event)

so after reloading, the texture id 1 and texture id 2 is missig (it gets transparent) but texture id 129..130.. and so on gets displayed (maybe its because of other issues, but the numbers 128,129,130) exspecially 128 is like its being something "signed 1 byte" or something.. I tried searching for "signed, byte, 128, 2^8" and other forms, but i dont find any.

**Comment by andrewtheone** [comment]
![image](https://cloud.githubusercontent.com/assets/798506/12071435/dbf4c3fe-b0ac-11e5-8481-42648a7dc50e.png)

gray- terr6
blue - terr128
and the right one which is fully transparent (but texture passed) is terr129

terr 129 has textures inside of terr3's texture (first terrain displayed with texture, terr1, terr2 is solid colors)

**Comment by andrewtheone** [comment]
SOLVED:

chunk.js:332

var maskCache = new Int16Array(4096),
    aomaskCache = new Uint16Array(4096)

changed 8 bit int and uint arrays to 16 bit arrays now it works :)

**Comment by andyhall** [comment]
Thanks! I pushed a fix for this. In the future if you want to submit pull requests for fixes like this I'd happily accept them.
