### ISSUE TITLE
How to get position of an entity?

### ISSUE THREAD

**Issue by EliteAsian123** [andyhall/noa#76]
How do I get the position of let's say, the player?

**Comment by andyhall** [comment]
Short answer: `noa.ents.getPosition(noa.playerEntity)`

Long answer: entity data all lives in components, and entity positions live in the `position` property of the state object of the `position` component. So the explicit way to get the data would be:

```js
var entID = noa.playerEntity  // 1
var compName = noa.ents.names.position  // "position"
var posdata = noa.ents.getState(entID, compName)
console.log(posdata.position)
```

However the `entities` module defines a bunch of accessors for often-used data, [here is where they're all defined](https://github.com/andyhall/noa/blob/master/src/lib/entities.js#L66-L94).

By the way, `noa` entity positions are always the *bottom-center* of the entity's AABB.

**Comment by EliteAsian123** [comment]
Okay thanks!
