### ISSUE TITLE
Andy I need a worm

### ISSUE THREAD

**Issue by levlups** [andyhall/noa#78]
how would I program in my worlddataneeded code a worm that adds air in the ground , but checks edges or puts hard block on chunk edges, because when I do something with air if I hit a chunk edge it leaves a whole in my map

**Comment by levlups** [comment]
or How do I understand check edges how to avoid them

**Comment by andyhall** [comment]
You mean a minecraft-style cave where there's a worm of air through the terrain, right? I don't know any good way to do this, but maybe someone else does.

For how chunk edges affect worldgen please see [this comment](https://github.com/andyhall/noa/issues/79#issuecomment-526913591).
