### ISSUE TITLE
Texture backface flip

### ISSUE THREAD

**Issue by andrewtheone** [andyhall/noa#8]
Hey!

Me again, I tried to solve this one on my own, but just cant figure it out.
Problem:

I give only 1 texture to a voxel. It displays perfectly. (I'm only interested in the side-faces (front, left, right, back, .... bottom and top doesnt matter). 3 out of 4 faces displays correctly but the back one is fliped vertically, any idea how to get rid of this?

**Comment by andyhall** [comment]
Weird, I haven't touched that code in a looong time. Is this with the vanilla engine, or did you tweak anything in the rendering or chunking code? If it's the standard engine, can it be minimally reproduced?

**Comment by andrewtheone** [comment]
its fully vanilla part

reproduction:
take a image, with some text on it (so it'll be easier to ditinquish if its flipped and if so in which direction)

register material, pass image as texture

place a block with the texted texture, walk around and up and down

**Comment by andyhall** [comment]
Hmm.. I see stuff horizontally flipped (2/4 sides) but not vertically.

Does this happen in the [testbed](http://andyhall.github.io/noa-testbed/)? E.g. for the "grassy dirt" blocks, is one of the sides rendering for you with the grass on the bottom? If so, can I have OS/browser/version details?

**Comment by andrewtheone** [comment]
No, i does not happen in the testbed

**Comment by andrewtheone** [comment]
I meant to say "on Y axis" when i said vertically, so yeah, if you stand in front of a block, whats on the right side on the front, that goes onto that left side on the backside of the block.. -if it makes any sense-

**Comment by andyhall** [comment]
I get you know, and this is fixed by 26b5ba6.

Thanks!
