### ISSUE TITLE
Is there a block update function?

### ISSUE THREAD

**Issue by EliteAsian123** [andyhall/noa#81]
Is there a block update function? So every tick, each block calls a function or something similar. In this case I want to make my cactus grow every once in a while.

**Comment by andyhall** [comment]
Hi - the way I do this is to use [custom block events](https://github.com/andyhall/noa/blob/master/src/lib/registry.js#L105-L108) to track when cactus blocks are added to or removed from the world, and then run a tick handler to occasionally update existing blocks.

E.g.:

```js
noa.registry.registerBlock( cactusID, {
    // block settings, material, opacity, etc...
    onSet: addCactus,
    onUnset: removeCactus,
    onLoad: addCactus,
    onUnload: removeCactus,
})

function addCactus(x,y,z) {    // remember there's a cactus at (x,y,z)...
function removeCactus(x,y,z) { // forget there's a cactus at (x,y,z)...
noa.on('tick', function() {    // do something with all current cactus blocks...
```

Block event meanings are explained [here](https://github.com/andyhall/noa/blob/master/HISTORY.md#0190), hope that helps.

**Comment by EliteAsian123** [comment]
Thanks for the answer! Sorry for asking a lot of questions!

**Comment by andyhall** [comment]
Not at all, please assume every question is something I've forgotten to document! Thanks!
