### ISSUE TITLE
Is there away to change block color when placing it 

### ISSUE THREAD

**Issue by levlups** [andyhall/noa#82]
this will be used to place for example a grass block of different shades for shadows 

like in this picture 
![shadows](https://user-images.githubusercontent.com/52762684/64492958-2f075a00-d248-11e9-9b62-d142ce877b00.jpg)

**Comment by andyhall** [comment]
Hi, so there is no feature like this currently. Here's the story on block colors at the moment.

When terrain is built, vertex colors are used for AO (shadows in corners) and for blocks whose material has a color but no texture. Blocks with a texture get white vertices.

It would be easy to change things such that vertex colors always get assigned even with textures, but I'm not certain whether that would color blocks the way you want.. it would depend on what going on with the different color channels (emissive etc).

As for lighting generally, to be honest I've not thought about it much as it's not needed for the game I'm personally working on. A more comprehensive approach to lighting, eg the way Minecraft does it with a 3D light map, would be possible but it's not something I'm planning on trying soon.
