### ISSUE TITLE
Better (?) objectBlock chunk building

### ISSUE THREAD

**Issue by PandawanFr** [andyhall/noa#83]
Hey,

I've done a bit of research on [Babylon's `SolidParticleSystem`](https://doc.babylonjs.com/how_to/solid_particle_system), which is used for objectBlocks (blocks with custom meshes), and found that they can actually be updated. I saw that noa simply replaces (removes and re-creates) its SPS every time a new objectBlock is placed in the chunk, which (I would think) probably affects performances.

I have yet to try changing the code so it can update the SPS rather than replace it but was wondering if this was a design decision or if changing it might be an improvement. It seems to me it would both improve performances and allow for some sort of dynamic blocks (through `SPS.updateParticle()`).

I've also looked into what would need to be changed:
1. The `objectMesher` used by the chunk should keep a reference to all of the SPS it creates so it can update them easily. (It could, perhaps, keep a map by blockID).
2. The `objectMesher.buildSPSforMaterialIndex()` method would have to use the previously created SPS and call `SPS.updateParticle()` (or create a new one if undefined, making sure to mark it as `updatable: true`).
3. Have some way of checking if the objectBlocks are dirty and call `SPS.setParticles()` in the `beforeRender` event in order to update the SPS's actual mesh.

Note: I haven't tested any of this, but it seems that this would be the only work required.

So yeah, I might try implementing it on my own but first would like to know if it's even worth it, if you have any insight, etc. (And if you want, I can submit a PR if it's all good :smile: ).

**Comment by andyhall** [comment]
The reason for the current behavior is that each object mesh SPS is created as [non-updatable](https://github.com/andyhall/noa/blob/master/src/lib/objectMesher.js#L156), which improves steady-state performance (according to the docs anyway).

That is, each SPS is more costly to build, but large numbers of them should perform better afterwards. I'm assuming that a typical game world will have hundreds or thousands of chunks in memory, compared to only a few needing to be rebuilt at a given time, so this seems like a reasonable tradeoff.

But I have not done any deep performance testing. From the profiling I have done, my best guess is that object blocks don't have a measurable impact on typical worlds, either on the meshing side or the rendering side.

**Comment by PandawanFr** [comment]
Hmmm, sounds reasonable.

I also was considering changing it because Babylon’s lights are fairly limited. So I wanted to use the includeOnlyMeshes option which allows me to specify which meshes should be affected by the light, but I was encountering issues with the SPS creating an entirely new mesh every time it changed. (Do you have any suggestions for this issue? If not, I’ll try implementing the solution I posted above and see how performances are impacted).

**Comment by andyhall** [comment]
Hi, to be honest I think that lighting and terrain meshes is a more fundamental problem, and I haven't thought much about it. But offhand it doesn't seem like changing the SPS behavior would help so much. Don't you have a parallel problem with regular terrain meshes, since the terrain mesher makes a new mesh each time it runs? Another complication is, even with the change you're suggesting object meshes would still be created/destroyed when the last/first object block is created/destroyed in a given chunk. (I think this additionally separately for separate custom mesh materials, so a chunk could have differing numbers of object block meshes at varying times, even if updatable SPSes are used.

Thinking out loud, would it suit your case if there was a way to query all the "world" (terrain + object block) meshes in a given region, and also get an event when they change? Or another idea would be for the game client to "register" lights and then have `noa` try to manage the list of meshes affected by them, but that sounds complicated and brittle...

**Comment by PandawanFr** [comment]
Hmm, I didn't even think about that. 
I checked and you're right. I had it set up on creation of the light to use the terrainMesh, but didn't realize that it no longer worked after setting blocks.

I got it to work by adding a `chunkMeshUpdated` event in the world, which is called in `processMeshingQueues` after updating the chunk's mesh.

While testing this, I encountered a different issue which I haven't looked into yet, when placing an objectBlock at the edge of a chunk, [it is registered in both chunks and creates two duplicate meshes](https://streamable.com/hj8s5). Is that something you've encountered before?

**Comment by andyhall** [comment]
Hi, okay I will add a suitable event here, and have it up in #develop pretty soon. (I'm currently working on a different change that affects object and terrain meshing, so I'll wait until after that's done to avoid merging woes).

The duplicate meshes must be a bug, nice catch! I will squash that at the same time.

**Comment by andyhall** [comment]
Okay, the duplicate logic for object blocks on chunk borders should be fixed in the latest #develop updates..

**Comment by PandawanFr** [comment]
Awesome, thanks! I guess I'll close this issue since the dynamic SolidParticleSystem might not really be worth it.

**Comment by andyhall** [comment]
Thanks, I'll open another issue for the terrain/object mesh events we discussed.
