### ISSUE TITLE
Moving to ES6 classes?

### ISSUE THREAD

**Issue by PandawanFr** [andyhall/noa#85]
It would be nice if noa could be moved to ES6+ completely by moving from prototypes to classes, using let & const, arrow functions, etc. 

This provides much more readable code and still works on almost every platform. It would also improve intellisense/jsdoc as the code analysis is better with classes (it's easier to document noa as a class rather than a function with prototypes when it's meant to be a class).

Noa, right now, is in this in-between state where it uses ES5 everywhere except for import statements, which are ES6. I believe upgrading would be a major improvement.

**Comment by andyhall** [comment]
Hi, thanks for the suggestion! Here's the current state of things:

 - Arrow functions are great - much of the engine was written before they were available but I often add them in when updating things. If you see spots badly in need of this let me know.

 - ES6 classes, I haven't really considered. I think of them as just sugar for prototypes, but if there's a specific benefit to e.g intellisense that would be worth switching. Can you describe in more detail what change would bring what benefit?

 - For let and const, I've basically ignored them for performance reasons.  I believe they no longer trigger deopts but don't know any further details. I'm pretty much holding off on them until I start hearing about cases where they perform better than var.

**Comment by PandawanFr** [comment]
Hey, those are some valid points, here are a couple of reasons/things that I think the code should be updated:
- Yes, arrow functions are great. :)

- For ES6\* classes, I was more considering them on the premise that they make code simpler to read, it's easier to understand than `SomeClass.prototype.someProperty = ...`; furthermore intellisense sometimes works better when using classes, [for example when using `extends` vs prototype inheritance](https://streamable.com/2s4w7). 
(Note: don't worry about the red underlines, these are because my project is in TypeScript so `any` type errors are reported). 

- For let and const, [it seems that they no longer have performance issues](https://stackoverflow.com/a/40070682), but the main reason why I like using them is that they make it easier to understand the code. Their scoping makes it less likely to produce issues with values overriding each other and I especially like const because you know for a fact that that given value isn't supposed to change. For example, [default options](https://github.com/andyhall/noa/blob/master/src/index.js#L38) could be marked as const to show that they can't/shouldn't be modified. 

- There is also object/array destructuring, for things like position which always comes in a 3D array `const [x, y, z] = position`. This seems especially useful when coupled with the `gl-vec3` library, which uses arrays for everything.

- There are some other things that could be used but have not looked into where/how much they might be useful for noa such as default parameters, template literals, etc.

\* Also [classes are getting private fields and methods soon](https://github.com/tc39/proposal-private-methods#private-methods-and-fields) so that could make the code cleaner instead of having functions all over the place and using an underscore to show that fields should be private. But I can understand why one wouldn't want to add every function into the class so this isn't that important.


Now I do understand that some of these might have some performance impacts, though I am not sure which ones, and to what degree so that would need to be looked into.

PS: Sorry for long post

---

Also, this isn't very much related to ES6 specifically, but after you release your changes ([which you mentioned in the other issue](https://github.com/andyhall/noa/issues/83#issuecomment-530647723)), I'll see if I can help and push a PR to improve documentation. I see a lot of opportunity to use `@typedef` to describe what objects look like, options, etc.

**Comment by andyhall** [comment]
Hi, sorry for the late reply again. But I appreciate the issue, it's useful to touch on all things ES6-like.

 * ES6 classes: I think it's right to adopt this sooner or later. But it's the kind of change that would touch almost everything in the repo, so I think I need to try it out locally and get used to it a little.
 * Object destructuring: I'm definitely avoiding this, for performance reasons and I think it's a little magical for game engine internals 😄This also applies to spread syntax, rest parameters, and so forth. I don't positively know how much each one affects performance, but for game engine internals I generally want things to be maximally explicit, and minimally magical.
 * Template literals, I like a lot, if you see a spot that isn't using them feel free to file or PR!
 * Let and const - I know about that link, as I've been trying to keep an eye on whether v8 starts optimizing them in new ways. But as a purely stylistic matter, to be honest I'm not a fan of them (e.g. the way `const` affect object properties, so using it on the default options object wouldn't have the desired effect). So for now I'm not planning to adopt let/const, but I probably will if there starts being a perf benefit.

PS I did push the other changes I mentioned, so feel free to hack away! (and also let me know if those changes break your code - they're kind of nontrivial)

**Comment by PandawanFr** [comment]
Hmm okay. I’d be especially looking forward to ES6 classes. 

Yeah so I have [a fork](https://github.com/PandawanFr/noa) that I’ll try PRing some of the changes once I’m done with them.

I don’t think I’ll implement the major ES6 classes stuff because I think it’s better if u did that. But I’ll try some of the other stuff. Right now I’m a bit struggling with the documentation because the JSDoc syntax is slightly different from TypeScript typings so I can’t specify Vector3s as “[number, number, number],” I’ll look more into it.

**Comment by PandawanFr** [comment]
Hey, so I've been fighting with the TypeScript compiler for a while now, trying to get things to work with noa: TypeScript can't analyze "extends" when using constructor functions (ES5 classes). This is preventing me from getting intellisense for EntComp and EventEmitter.

So I was wondering if I could work on (and submit) a PR which moves everything to ES6 classes because I'd rather not have to go on with a fork all the time. 

(btw, VSCode uses the TypeScript compiler under the hood for JS intellisense, so this would also benefit JS users).

**Comment by andyhall** [comment]
Hi, sorry for the crazy late reply, I forgot about this.

High level answer is: the only reason I haven't adopted ES6 classes is the lack of private/local variables (and the proposed syntax for them is so ugly! 😦..). However, getting code hints is a huge benefit and I am happy to compromise on my feelings if it makes code hints work.

So, I'm not personally working with TS and I'd be hesitant to migrate the whole engine to TS, but if adopting ES6 would make code hints work for TS users I'd happily take that PR. If you'd be willing to do that it'd be great - I don't want to attempt it, because without a TS environment I can't easily check if the intended benefits are working or not.

For timing, since this PR would touch most of the repo, it'd be good to do it somewhere stable. I'm just about to merge `#develop` into main as `v0.27.0`, and I don't have any big changes queued up after that. So if you'd still like to do this, I think basing it `v0.27` would be ideal. (But please work in #develop!)

Also one question: do you have a preferred way of doing local vars? Generally I have been using `this._foo` style underbar prefixes. But in some cases, where I have an ES5 class with lots of local vars, when I migrate to an ES6 class I pull them all into a single object called `this._state`. But I don't think there are many classes in noa that would need this, mostly when I moved to `import/export` I got rid of most of the private vars.

Anyway let me know if you have questions but please feel free to do this if you have time!

**Comment by PandawanFr** [comment]
Hmm, I'll see if I can submit a PR... Not sure tho.

> do you have a preferred way of doing local vars?

So for private class properties, I usually do `this._foo` but for variables inside methods/member functions, I use the regular name like `foo` since they're only accessible inside the function itself so there's no confusion there.

I rarely use `this._state` but I do sometimes group properties into an object when they're very similar. (But in this case, a state variable is too "generic," and wouldn't make much sense).

**Comment by andyhall** [comment]
Closing this as it should be overridden by the TS migration branch and/or #135.
