### ISSUE TITLE
Question about max blocks in registry

### ISSUE THREAD

**Issue by geggleto** [andyhall/noa#93]
Was there a reason for the 256 limit in the registry?

Seems extremely small :)

**Comment by andyhall** [comment]
Hi, I think the limit is currently 512 but I could be wrong. The reason for it is that at runtime voxel data is packed into `Uint16` arrays, with 9 bits being the voxel ID, 3 bits for flags (solidity, opacity, and whether it's an object block), and the rest reserved for future use.

The eventual plan for the extra bits is to indicate variations of a given voxel (I think minecraft does this with e.g. colors of wool blocks), but there isn't any code for that in the library yet.
