### ISSUE TITLE
Animated Textures

### ISSUE THREAD

**Issue by Roy-Ermers** [andyhall/noa#98]
Hello Andy,

For my game I need animated water, is this possible with the current state of the engine?

Roy Ermers

**Comment by andyhall** [comment]
Hi, thanks for trying the engine. The way to do this is, first [register a block material](https://github.com/andyhall/noa/blob/master/doc/API.md#Registry+registerMaterial) for the water blocks, and as the last argument pass in an instance of a BabylonJS material. Then, when the engine creates terrain with water blocks, those meshes will be assigned the Babylon material you passed in. And then you can later on modify that material however you like - change the texture, or the texture UVs, etc.

There's sample code for registering a block with a custom material in the testbed app. [This bit](https://github.com/andyhall/noa-examples/blob/master/src/test/registration.js#L37-L42) creates the material and registers it, and then [this bit](https://github.com/andyhall/noa-examples/blob/master/src/test/registration.js#L58) registers a block type using that material.

Note that you might have to do something Babylon-specific to make the updated material settings render - like calling [`material.unfreeze`](https://doc.babylonjs.com/api/classes/babylon.material#unfreeze) or something like that. I'm not super sure on the details but the BJS forum is really helpful if you have issues with the non-noa side of things.

**Comment by Roy-Ermers** [comment]
Hey thanks for the fast response, I already figured out you could add custom materials, but the animations didn't work. Turns out I missed the material.unfreeze function.

**Comment by Roy-Ermers** [comment]
I've tested it, but the faces that uses the materials are all white, 
![image](https://user-images.githubusercontent.com/8841123/80397171-08b92c00-88b6-11ea-9dbe-857fdc7f5277.png)

i've used material.unfreeze()

**Comment by andyhall** [comment]
Hi, I'm guessing this is a Babylon/material issue - e.g. the material's emissive color is overwhelming the diffuse, or vice-versa? I'd probably jump into devtools and twiddle them to see what's going on.

If you used [`rendering.makeStandardMaterial`](https://github.com/andyhall/noa/blob/master/src/lib/rendering.js#L289), by the way, note that it sets some colors by default, so you may need to unset them depending on which texture channel you used, etc.

**Comment by Roy-Ermers** [comment]
Hi, it still doesn't work, do you know if the class `CustomProceduralTexture` is supported as texture?

**Comment by andyhall** [comment]
I've never tried it, but I'd imagine so? Broadly speaking, noa does a lot of management of the Babylon scene's mesh positions and vertices, but for materials and lights it just sets things up initially and then leaves everything alone. So working with those is mostly the same as it would be in a regular Babylon scene, outside of noa. As such, when I was setting up animated textures in my world I found it useful to test my code in the Babylon playground, and then port things over when it worked. But I haven't worked with procedural textures, so there could be issues I don't know about.

**Comment by Roy-Ermers** [comment]
hey i've tried the whole evening to fix this, but even with ShaderMaterials it doesn't work. I'm convinced that the problem occurs in my fragment shader. Could you maybe spot the error?
```glsl
#ifdef GL_ES
    precision highp float;
#endif

uniform float frameTime;
uniform vec2 spriteSize;
uniform vec2 spriteSheetSize;
uniform vec4 waterColor;
uniform float time;
uniform sampler2D water;
varying vec2 vUV;

void main(void) {
	float index = mod(time, frameTime); 
	
	float w =  spriteSheetSize.x;
	float h = spriteSheetSize.y;

	float dx = spriteSize.x / w;
	float dy = spriteSize.y / h;

	float cols = w / spriteSize.x;

	float col = mod(index, cols);
	float row = floor(index / cols);

	vec2 uv = vec2(dx * vUV.x + col * dx, 1.0 - dy - row * dy + dy * vUV.y);
   
	gl_FragColor = texture2D(water, uv);
}
```

**Comment by andyhall** [comment]
Hi, I'm not sure about the frag shader, but if a regular texture isn't showing up for you then I would imagine a procedural texture would have the same issue, so I think that would need to be fixed first.

For me, adding code like this to the testbed app worked. Can you try this as a starting point?

```js
    var animMat = noa.rendering.makeStandardMaterial('animMat')
    animMat.diffuseTexture = new Texture('textures/stone.png', scene)
    noa.registry.registerMaterial('test', null, null, false, animMat)
    var testID = noa.registry.registerBlock(15, { material: 'test' })
    
    setInterval(() => {
        animMat.diffuseTexture.uOffset += 0.01
        animMat.diffuseTexture.vOffset += 0.01
    }, 50)

    setTimeout(() => {
        noa.setBlock(testID, 1, 3, 5)
    }, 1000)
```

**Comment by Roy-Ermers** [comment]
Thanks i fixed it! I had to use a sprite sheet so the code is slightly different. Gonna leave this here for future references.
```js
			material.diffuseTexture.wrapV = Texture.WRAP_ADDRESSMODE;
			material.diffuseTexture.vScale = 1 / frames;

			material.unfreeze();

			//register loop
			scene.registerBeforeRender(() => {
				time++;
				const currentFrame = Math.floor(time / frameTime) % frames;
				material.diffuseTexture.vOffset = 1 / frames * currentFrame;
			});

```

**Comment by andyhall** [comment]
Ah, cheers for sharing the solution!

If you're using sprite sheets you might check this out: [babylon-atlas](https://github.com/andyhall/babylon-atlas). It's quite a while since I touched that code, but it works in my project and you might find the source useful.

**Comment by Roy-Ermers** [comment]
Damn, that was exactly what I needed. Thanks!
