### ISSUE TITLE
256 block limit?

### ISSUE THREAD

**Issue by Heath123** [andyhall/noa#99]
You said in #93 that you can register 512 blocks, but here:
https://github.com/andyhall/noa/blob/65e6c88ad64c05055190ba42255e2b530455f221/src/lib/registry.js#L35
it's limited to 255. Is there a reason for that or is it an oversight?
Thank you

**Comment by andyhall** [comment]
Ah, nice catch! That line is wrong, the logic that stores voxel data uses [nine bits](https://github.com/andyhall/noa/blob/master/src/lib/constants.js#L17-L18) for the voxel ID. I'll fix this next release.

**Comment by Heath123** [comment]
Thank you!

**Comment by andyhall** [comment]
Should be fixed in #develop, so #master will be fixed in next update.
